@BookingHotelAPI_HostAddress = https://localhost:7023
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=


GET {{BookingHotelAPI_HostAddress}}/api/countries
# X-Api-Key: {{apiKey}}
# Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYThhYjc1Mi1lOWEyLTRiNTItYjNkMS0yYmM3YWI1Y2Q1NGYiLCJlbWFpbCI6InVzc3NzQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJjODAwZTY0OS00NzBmLTRmNDctOWIyMS0yMzliYzE1Yzg5ZTMiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJleHAiOjE3NjczNTY0OTAsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.4DgmPheljs7jyh1J6rSHqIX1Hq_AdwDSnkuBw3HFzQQ
###

POST {{BookingHotelAPI_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "TCountriiiiiii",
  "ShortName": "TC"
}

###

@Id=8
DELETE {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}

###

GET {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}

###

PUT {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "countryId": 8,
  "Name": "3333",
  "ShortName": "TC"
}

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels

###

POST {{BookingHotelAPI_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "TTTTest Hotel",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5
}

###
@id=13
DELETE {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}

###

PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 13,
  "Name": "III",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5,
  "country": null
}

###

POST {{BookingHotelAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "ussss@localhost.com",
  "password": "P@ssword1",
  "firstName":"First",
  "lastName": "Last"

}

###
POST {{BookingHotelAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ussss@localhost.com",
  "password": "P@ssword1"
}

###
