@BookingHotelAPI_HostAddress = https://localhost:7023
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=


GET {{BookingHotelAPI_HostAddress}}/api/countries
# X-Api-Key: {{apiKey}}
# Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYThhYjc1Mi1lOWEyLTRiNTItYjNkMS0yYmM3YWI1Y2Q1NGYiLCJlbWFpbCI6InVzc3NzQGxvY2FsaG9zdC5jb20iLCJqdGkiOiI3Y2NkZWE0MC1lOWE1LTQ0ODYtYWVjNS1kY2IyNjczZmY3ZmUiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJleHAiOjE3NjczNTg1NjMsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.Rk-r3gKU7a7vHbsnXgl6DAnp7Qk08TjOuyzb2AMAR2E

###
POST {{BookingHotelAPI_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "TCountriiiiiii",
  "ShortName": "TC"
}

###

@Id=8
DELETE {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}

###

GET {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}

###

PUT {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "countryId": 8,
  "Name": "3333",
  "ShortName": "TC"
}

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels

###

POST {{BookingHotelAPI_HostAddress}}/api/hotels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIwYjJkYzAzZS1mNGU0LTRlN2MtYjIyMC04M2I0YTVhYzk3MzQiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3MzU4Njk0LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.aS5FJjQK-gRQ_FcWKMon6Z14SfBSWpTf87QKEyEr7bk
{
  "Name": "Admint Hotel",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5
}

###
@id=16
DELETE {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}

###

PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 17,
  "Name": "III",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5,
  "country": null
}

###

POST {{BookingHotelAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "P@ssword1",
  "firstName":"First",
  "lastName": "Last",
  "role":"Administrator"

}

###
POST {{BookingHotelAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "P@ssword1"
}

###
