@BookingHotelAPI_HostAddress = https://localhost:7023
@json = application/json
@apiKey=dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
### Variables
@json = application/json
@hotelId=3
@bookingId=7
@today={{$localDatetime iso8601}} 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzYzIxODRiNS1kOGExLTQyYzAtYjNhMy01ZGMzMjJlOTFjOTMiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NTI1NjU5LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.UXc85LBYKwwfe6A97TOz-fFui02KEaKksZyT8QZ1bgM

# Get Country Hotels - Large Page Size
GET {{HotelListing.Api_HostAddress}}/api/countries/{{countryId}}/hotels?pageNumber=1&pageSize=20
Authorization: Bearer {{token}}


###
GET {{BookingHotelAPI_HostAddress}}/api/countries?search=K
# X-Api-Key: {{apiKey}}
# Authorization: Basic dXNlcjFAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=
Authorization: Bearer {{token}}

###
POST {{BookingHotelAPI_HostAddress}}/api/countries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "T",
  "ShortName": "TC"
}

###

@Id=5
DELETE {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiI1MGMyYmQ0NS03OGE0LTRhYWMtOTEzMy1kNjY2Y2MwNzZkNmUiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUxODE2LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.tMVQPR3W1zj3yDsFNItEPszHapN-ZoBzZu1WATwyVFc
###

GET {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMmU4Njg5OC05OWU0LTRmODgtYjEwZi1lYjA2ODljNTY5YzIiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUxMzY1LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.HbuvXMbAZH9Ci_uBrpLea53_-xk3n4i2FdtRlFkOOEk
###

PUT {{BookingHotelAPI_HostAddress}}/api/countries/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMmU4Njg5OC05OWU0LTRmODgtYjEwZi1lYjA2ODljNTY5YzIiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUxMzY1LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.HbuvXMbAZH9Ci_uBrpLea53_-xk3n4i2FdtRlFkOOEk

  "countryId": 5,
  "Name": "3333",
  "ShortName": "TC"
}

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels?search=Kingston
Authorization: Bearer {{token}}
###

POST {{BookingHotelAPI_HostAddress}}/api/hotels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmMmU4Njg5OC05OWU0LTRmODgtYjEwZi1lYjA2ODljNTY5YzIiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUxMzY1LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.HbuvXMbAZH9Ci_uBrpLea53_-xk3n4i2FdtRlFkOOEk
 {
  "Name": "Adin Hotel",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5
}

###
@id=15
DELETE {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzZDAwMTI3Zi00MzNlLTQ1YjYtOTA5MS1jNTM1ODQ3Y2YzZGYiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUyMTc2LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ._tsqZmfzhRa51-A-BtbhLo7UKBVvm23iMsCxXU-FTy8
###

GET {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzZDAwMTI3Zi00MzNlLTQ1YjYtOTA5MS1jNTM1ODQ3Y2YzZGYiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUyMTc2LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ._tsqZmfzhRa51-A-BtbhLo7UKBVvm23iMsCxXU-FTy8
###
###

PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGViNmJmMC0wMzAzLTQ0MTItOTU5My0xMzcxZWM0YmMxYTQiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzZDAwMTI3Zi00MzNlLTQ1YjYtOTA5MS1jNTM1ODQ3Y2YzZGYiLCJuYW1lIjoiTGFzdCwgRmlyc3QiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzY3NDUyMTc2LCJpc3MiOiJIb3RlbExpc3RpbmdBUEkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ._tsqZmfzhRa51-A-BtbhLo7UKBVvm23iMsCxXU-FTy8
{
  "Id": 13,
  "Name": "III",
  "Address": "123",
  "Rating": 4.5,
  "CountryId": 5,
  "country": null
}

###

POST {{BookingHotelAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "Hotel_Admin@localhost.com",
  "password": "P@ssword1",
  "firstName":"First",
  "lastName": "Last",
  "role":"Hotel Admin"

}

###
POST {{BookingHotelAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@localhost.com",
  "password": "P@ssword1"
}

###
 # 

  "email": "Hotel_Admin@localhost.com",
  "password": "P@ssword1"
###
PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{hotelId:int}/bookings/{bookingId:int}/admin/cancel

###

PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{hotelId:int}/bookings/{bookingId:int}/admin/confirm
Authorization: Bearer {{token}}
###

PUT {{BookingHotelAPI_HostAddress}}/api/hotels/{hotelId:int}/bookings/{bookingId:int}/cancel

###

@countryId=9
GET {{BookingHotelAPI_HostAddress}}/api/Countries/{{countryId}}/hotels
Authorization: Bearer {{token}}
###

GET {{BookingHotelAPI_HostAddress}}/api/countries/{countryId:int}/hotels

###

GET {{BookingHotelAPI_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
###

GET {{BookingHotelAPI_HostAddress}}/api/hotels/{hotelId:int}/bookings
Authorization: Bearer {{token}}
###

GET {{BookingHotelAPI_HostAddress}}/api/hotels/{hotelId:int}/bookings/admin
Authorization: Bearer {{token}}
###
